@startuml ADOPSE_uml
!theme toy
frame "Front end" {
  enum ButtonType {
    Radio
    Checkbox
  }
  class Button {
    -ButtonType buttonType
    -String value

  }
  class Question {
    -ButtonType buttonType
    -int buttonNum
    -String[] buttonDescriptions
    -String question
    ---
    -void render()
  }
  ButtonType -up- Button
}
@enduml